### ISSUE TITLE
Idea: Read a single config.{toml,json,jsonc, yml).

### ISSUE THREAD

**Issue by SARDONYX-sard** [SARDONYX-sard/dotfiles#10]
- Create a single config.{toml,json,jsonc,yml} and read it in the dotfiles so that the user side can freely select the applications to be included.

## Example

```toml
[git]
username = "Hello"
email = "FooBar.gmail.com"
```
=> read it on dotfiles.
